CREATE SCHEMA IF NOT EXISTS PILOTOS DEFAULT CHARACTER SET latin1;
USE PILOTOS;

CREATE TABLE IF NOT EXISTS PILOTOS (
    COD_PILOTOS VARCHAR(3),
    PIL_NOMBRE VARCHAR(15) NOT NULL,
    NACIONALIDAD ENUM("Brasileña","Española","Inglesa","Alemana"),
    FECHA_NACIMIENTO DATETIME NOT NULL,
    DEBUT YEAR,
    CHECK (DEBUT BETWEEN 1999 AND 2020),
    PRIMARY KEY (COD_PILOTOS)
)
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS CIRCUITOS (
    CIR_NOMBRE VARCHAR(15),
    PAIS VARCHAR(15),
    TIPO VARCHAR(15),
    LONGITUD FLOAT,
    DISENADOR VARCHAR(20),
    CHECK (LONGITUD BETWEEN 2400 AND 9999.9),
    PRIMARY KEY (CIR_NOMBRE)
)
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS CARRERAS (
    NOMBREGP VARCHAR(15),
    ANIO VARCHAR(4),
    FECHAHORAINICIO DATETIME NOT NULL,
    CIRCUITO VARCHAR(15),
    CHECK (TIME(FECHAHORAINICIO) BETWEEN '13:00:00' AND '21:30:00'),
    PRIMARY KEY (NOMBREGP, ANIO),
    CONSTRAINT FK_CIRCUITOS
        FOREIGN KEY (CIRCUITO)
        REFERENCES CIRCUITOS (CIR_NOMBRE)
)
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS RESULTADOS (
    NOMBREGP VARCHAR(15),
    ANIO VARCHAR(4),
    COD_PILOTOS VARCHAR(3),
    PUESTO INT,
    DISTANCIAGANADOR VARCHAR(9),
    CHECK (PUESTO < 99),
    PRIMARY KEY (NOMBREGP, ANIO, COD_PILOTOS),
    CONSTRAINT FK_NOMBREGP
        FOREIGN KEY (NOMBREGP, ANIO)
        REFERENCES CARRERAS (NOMBREGP,ANIO),
    CONSTRAINT FK_COD_PILOTOS
        FOREIGN KEY (COD_PILOTOS)
        REFERENCES PILOTOS (COD_PILOTOS)
)
ENGINE = INNODB;
