-- MySQL Script generated by MySQL Workbench
-- Sun Jan 23 17:33:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema museos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema museos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `museos` DEFAULT CHARACTER SET utf8 ;
USE `museos` ;

-- -----------------------------------------------------
-- Table `museos`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museos`.`autores` (
  `id_autor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `fecha_fal` DATE NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museos`.`museos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museos`.`museos` (
  `id_museos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_museos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museos`.`obras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museos`.`obras` (
  `id_obras` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_museos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_obras`),
  INDEX `fk_idMuseos_idx` (`id_museos` ASC) VISIBLE,
  CONSTRAINT `fk_idMuseos`
    FOREIGN KEY (`id_museos`)
    REFERENCES `museos`.`museos` (`id_museos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museos`.`obra_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museos`.`obra_autor` (
  `id_obras` INT UNSIGNED NOT NULL,
  `id_autor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_obras`, `id_autor`),
  INDEX `fk_idAutor_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_idObras`
    FOREIGN KEY (`id_obras`)
    REFERENCES `museos`.`obras` (`id_obras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idAutor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `museos`.`autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
