<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pokedex">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="151">
                <xs:element name="pokemon">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="vida" type="xs:integer" />
                            <xs:element name="ataque" type="xs:integer" />
                            <xs:element name="defensa" type="xs:integer" />
                            <xs:element name="tipo" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>