-- 1 

SELECT J.NICK, COUNT(PA.ID_PARTIDA) AS TOTAL_PARTICIPACIONES, SUM(PA.PUNTOS) AS SUMA_PUNTOS
FROM JUGADORES J
INNER JOIN PERSONAJES PER
ON J.ID_JUGADOR = PER.ID_JUGADOR
INNER JOIN PARTICIPACIONES PA 
ON PER.ID_PERSONAJE = PA.ID_PERSONAJE
GROUP BY J.ID_JUGADOR, J.NICK;

-- 2

SELECT PE.NOMBRE, PA.PUNTOS
FROM PERSONAJES PE
INNER JOIN PARTICIPACIONES PA
ON PE.ID_PERSONAJE = PA.ID_PERSONAJE
WHERE PA.PUNTOS = (SELECT MAX(PUNTOS) FROM PARTICIPACIONES);


-- 3



-- 4

-- SELECT J.NICK, COUNT(DISTINCT PE.ID_PERSONAJE ) as NUMERO_PERSONAJES , sum(par.puntos) AS SUMA_PUNTOS
-- from JUGADORES J 
-- INNER JOIN PERSONAJES PE 
-- ON J.ID_JUGADOR = PE.ID_JUGADOR
-- INNER JOIN PARTICIPACIONES PAR 
-- ON PE.ID_PERSONAJE = PAR.ID_PERSONAJE
-- GROUP BY J.ID_JUGADOR, J.NICK
-- HAVING COUNT(DISTINCT PE.ID_JUGADOR) > 1 AND SUM(PAR.PUNTOS) > 3000;

-- NO SE POR QUE NO FUNCIONA.


-- 5 

SELECT J.NICK , COUNT(DISTINCT PA.MAPA) AS MAPAS_DISTINTOS
FROM JUGADORES J
INNER JOIN PERSONAJES PE 
ON J.ID_JUGADOR = PE.ID_JUGADOR
INNER JOIN PARTICIPACIONES PAR 
ON PE.ID_PERSONAJE = PAR.ID_PERSONAJE
INNER JOIN PARTIDAS PA 
ON PAR.ID_PARTIDA = PA.ID_PARTIDA
GROUP BY J.ID_JUGADOR, J.NICK
HAVING COUNT(DISTINCT PA.MAPA) >= 2;



