
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        if not Calculadora.objectName():
            Calculadora.setObjectName(u"Calculadora")
        Calculadora.resize(491, 600)
        self.centralwidget = QWidget(Calculadora)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(150, 160, 81, 71))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 160, 81, 71))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(260, 160, 81, 71))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(150, 250, 81, 71))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(260, 250, 81, 71))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(40, 250, 81, 71))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(150, 340, 81, 71))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(260, 340, 81, 71))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(40, 340, 81, 71))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(150, 430, 81, 71))
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(260, 430, 81, 71))
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(40, 430, 81, 71))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 10, 471, 111))
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(370, 340, 81, 71))
        self.pushButton_14 = QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(370, 430, 81, 71))
        self.pushButton_15 = QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(370, 160, 81, 71))
        self.pushButton_16 = QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(370, 250, 81, 71))
        Calculadora.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Calculadora)
        self.statusbar.setObjectName(u"statusbar")
        Calculadora.setStatusBar(self.statusbar)

        self.retranslateUi(Calculadora)

        QMetaObject.connectSlotsByName(Calculadora)
    # setupUi

    def retranslateUi(self, Calculadora):
        Calculadora.setWindowTitle(QCoreApplication.translate("Calculadora", u"Calculadora", None))
        self.pushButton.setText(QCoreApplication.translate("Calculadora", u"2", None))
        self.pushButton_2.setText(QCoreApplication.translate("Calculadora", u"1", None))
        self.pushButton_3.setText(QCoreApplication.translate("Calculadora", u"3", None))
        self.pushButton_4.setText(QCoreApplication.translate("Calculadora", u"5", None))
        self.pushButton_5.setText(QCoreApplication.translate("Calculadora", u"6", None))
        self.pushButton_6.setText(QCoreApplication.translate("Calculadora", u"4", None))
        self.pushButton_7.setText(QCoreApplication.translate("Calculadora", u"8", None))
        self.pushButton_8.setText(QCoreApplication.translate("Calculadora", u"9", None))
        self.pushButton_9.setText(QCoreApplication.translate("Calculadora", u"7", None))
        self.pushButton_10.setText(QCoreApplication.translate("Calculadora", u"0", None))
        self.pushButton_11.setText(QCoreApplication.translate("Calculadora", u"=", None))
        self.pushButton_12.setText(QCoreApplication.translate("Calculadora", u"<", None))
        self.pushButton_13.setText(QCoreApplication.translate("Calculadora", u"*", None))
        self.pushButton_14.setText(QCoreApplication.translate("Calculadora", u"/", None))
        self.pushButton_15.setText(QCoreApplication.translate("Calculadora", u"+", None))
        self.pushButton_16.setText(QCoreApplication.translate("Calculadora", u"-", None))
    # retranslateUi

