from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Primitiva(object):
    def setupUi(self, Primitiva):
        if not Primitiva.objectName():
            Primitiva.setObjectName(u"Primitiva")
        Primitiva.resize(679, 413)
        self.groupBox = QGroupBox(Primitiva)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 90, 111, 251))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(20, 30, 51, 17))
        self.checkBox_2 = QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(20, 60, 51, 17))
        self.checkBox_3 = QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(20, 100, 51, 17))
        self.checkBox_4 = QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(20, 140, 51, 17))
        self.checkBox_5 = QCheckBox(self.groupBox)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(20, 180, 51, 17))
        self.groupBox_3 = QGroupBox(Primitiva)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(130, 90, 521, 251))
        self.checkBox_6 = QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(20, 30, 31, 17))
        self.checkBox_7 = QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(20, 60, 31, 17))
        self.checkBox_8 = QCheckBox(self.groupBox_3)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(20, 100, 31, 17))
        self.checkBox_9 = QCheckBox(self.groupBox_3)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(20, 140, 31, 17))
        self.checkBox_10 = QCheckBox(self.groupBox_3)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(20, 180, 31, 17))
        self.checkBox_11 = QCheckBox(self.groupBox_3)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(60, 100, 31, 17))
        self.checkBox_12 = QCheckBox(self.groupBox_3)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(60, 30, 31, 17))
        self.checkBox_13 = QCheckBox(self.groupBox_3)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(60, 180, 31, 17))
        self.checkBox_14 = QCheckBox(self.groupBox_3)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(60, 60, 31, 17))
        self.checkBox_15 = QCheckBox(self.groupBox_3)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setGeometry(QRect(60, 140, 31, 17))
        self.checkBox_16 = QCheckBox(self.groupBox_3)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(110, 100, 31, 17))
        self.checkBox_17 = QCheckBox(self.groupBox_3)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setGeometry(QRect(110, 30, 31, 17))
        self.checkBox_18 = QCheckBox(self.groupBox_3)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setGeometry(QRect(110, 180, 31, 17))
        self.checkBox_19 = QCheckBox(self.groupBox_3)
        self.checkBox_19.setObjectName(u"checkBox_19")
        self.checkBox_19.setGeometry(QRect(110, 60, 31, 17))
        self.checkBox_20 = QCheckBox(self.groupBox_3)
        self.checkBox_20.setObjectName(u"checkBox_20")
        self.checkBox_20.setGeometry(QRect(110, 140, 31, 17))
        self.checkBox_21 = QCheckBox(self.groupBox_3)
        self.checkBox_21.setObjectName(u"checkBox_21")
        self.checkBox_21.setGeometry(QRect(150, 100, 31, 17))
        self.checkBox_22 = QCheckBox(self.groupBox_3)
        self.checkBox_22.setObjectName(u"checkBox_22")
        self.checkBox_22.setGeometry(QRect(150, 30, 31, 17))
        self.checkBox_23 = QCheckBox(self.groupBox_3)
        self.checkBox_23.setObjectName(u"checkBox_23")
        self.checkBox_23.setGeometry(QRect(150, 180, 31, 17))
        self.checkBox_24 = QCheckBox(self.groupBox_3)
        self.checkBox_24.setObjectName(u"checkBox_24")
        self.checkBox_24.setGeometry(QRect(150, 60, 31, 17))
        self.checkBox_25 = QCheckBox(self.groupBox_3)
        self.checkBox_25.setObjectName(u"checkBox_25")
        self.checkBox_25.setGeometry(QRect(150, 140, 31, 17))
        self.checkBox_30 = QCheckBox(self.groupBox_3)
        self.checkBox_30.setObjectName(u"checkBox_30")
        self.checkBox_30.setGeometry(QRect(190, 140, 31, 17))
        self.checkBox_28 = QCheckBox(self.groupBox_3)
        self.checkBox_28.setObjectName(u"checkBox_28")
        self.checkBox_28.setGeometry(QRect(190, 180, 31, 17))
        self.checkBox_27 = QCheckBox(self.groupBox_3)
        self.checkBox_27.setObjectName(u"checkBox_27")
        self.checkBox_27.setGeometry(QRect(190, 30, 31, 17))
        self.checkBox_29 = QCheckBox(self.groupBox_3)
        self.checkBox_29.setObjectName(u"checkBox_29")
        self.checkBox_29.setGeometry(QRect(190, 60, 31, 17))
        self.checkBox_26 = QCheckBox(self.groupBox_3)
        self.checkBox_26.setObjectName(u"checkBox_26")
        self.checkBox_26.setGeometry(QRect(190, 100, 31, 17))
        self.checkBox_31 = QCheckBox(self.groupBox_3)
        self.checkBox_31.setObjectName(u"checkBox_31")
        self.checkBox_31.setGeometry(QRect(230, 100, 31, 17))
        self.checkBox_32 = QCheckBox(self.groupBox_3)
        self.checkBox_32.setObjectName(u"checkBox_32")
        self.checkBox_32.setGeometry(QRect(230, 30, 31, 17))
        self.checkBox_33 = QCheckBox(self.groupBox_3)
        self.checkBox_33.setObjectName(u"checkBox_33")
        self.checkBox_33.setGeometry(QRect(230, 180, 31, 17))
        self.checkBox_34 = QCheckBox(self.groupBox_3)
        self.checkBox_34.setObjectName(u"checkBox_34")
        self.checkBox_34.setGeometry(QRect(230, 60, 31, 17))
        self.checkBox_35 = QCheckBox(self.groupBox_3)
        self.checkBox_35.setObjectName(u"checkBox_35")
        self.checkBox_35.setGeometry(QRect(230, 140, 31, 17))
        self.checkBox_36 = QCheckBox(self.groupBox_3)
        self.checkBox_36.setObjectName(u"checkBox_36")
        self.checkBox_36.setGeometry(QRect(270, 100, 31, 17))
        self.checkBox_37 = QCheckBox(self.groupBox_3)
        self.checkBox_37.setObjectName(u"checkBox_37")
        self.checkBox_37.setGeometry(QRect(270, 27, 31, 20))
        self.checkBox_38 = QCheckBox(self.groupBox_3)
        self.checkBox_38.setObjectName(u"checkBox_38")
        self.checkBox_38.setGeometry(QRect(270, 180, 31, 17))
        self.checkBox_39 = QCheckBox(self.groupBox_3)
        self.checkBox_39.setObjectName(u"checkBox_39")
        self.checkBox_39.setGeometry(QRect(270, 60, 31, 17))
        self.checkBox_40 = QCheckBox(self.groupBox_3)
        self.checkBox_40.setObjectName(u"checkBox_40")
        self.checkBox_40.setGeometry(QRect(270, 140, 31, 17))
        self.checkBox_41 = QCheckBox(self.groupBox_3)
        self.checkBox_41.setObjectName(u"checkBox_41")
        self.checkBox_41.setGeometry(QRect(310, 100, 31, 17))
        self.checkBox_42 = QCheckBox(self.groupBox_3)
        self.checkBox_42.setObjectName(u"checkBox_42")
        self.checkBox_42.setGeometry(QRect(310, 30, 31, 17))
        self.checkBox_43 = QCheckBox(self.groupBox_3)
        self.checkBox_43.setObjectName(u"checkBox_43")
        self.checkBox_43.setGeometry(QRect(310, 180, 31, 17))
        self.checkBox_44 = QCheckBox(self.groupBox_3)
        self.checkBox_44.setObjectName(u"checkBox_44")
        self.checkBox_44.setGeometry(QRect(310, 60, 31, 17))
        self.checkBox_45 = QCheckBox(self.groupBox_3)
        self.checkBox_45.setObjectName(u"checkBox_45")
        self.checkBox_45.setGeometry(QRect(310, 140, 31, 17))
        self.checkBox_46 = QCheckBox(self.groupBox_3)
        self.checkBox_46.setObjectName(u"checkBox_46")
        self.checkBox_46.setGeometry(QRect(350, 100, 31, 17))
        self.checkBox_47 = QCheckBox(self.groupBox_3)
        self.checkBox_47.setObjectName(u"checkBox_47")
        self.checkBox_47.setGeometry(QRect(350, 30, 31, 17))
        self.checkBox_48 = QCheckBox(self.groupBox_3)
        self.checkBox_48.setObjectName(u"checkBox_48")
        self.checkBox_48.setGeometry(QRect(350, 180, 31, 17))
        self.checkBox_49 = QCheckBox(self.groupBox_3)
        self.checkBox_49.setObjectName(u"checkBox_49")
        self.checkBox_49.setGeometry(QRect(350, 60, 31, 17))
        self.checkBox_50 = QCheckBox(self.groupBox_3)
        self.checkBox_50.setObjectName(u"checkBox_50")
        self.checkBox_50.setGeometry(QRect(350, 140, 31, 17))
        self.checkBox_51 = QCheckBox(self.groupBox_3)
        self.checkBox_51.setObjectName(u"checkBox_51")
        self.checkBox_51.setGeometry(QRect(390, 100, 31, 17))
        self.checkBox_52 = QCheckBox(self.groupBox_3)
        self.checkBox_52.setObjectName(u"checkBox_52")
        self.checkBox_52.setGeometry(QRect(390, 30, 31, 17))
        self.checkBox_53 = QCheckBox(self.groupBox_3)
        self.checkBox_53.setObjectName(u"checkBox_53")
        self.checkBox_53.setGeometry(QRect(390, 180, 31, 17))
        self.checkBox_54 = QCheckBox(self.groupBox_3)
        self.checkBox_54.setObjectName(u"checkBox_54")
        self.checkBox_54.setGeometry(QRect(390, 60, 31, 17))
        self.checkBox_55 = QCheckBox(self.groupBox_3)
        self.checkBox_55.setObjectName(u"checkBox_55")
        self.checkBox_55.setGeometry(QRect(390, 140, 31, 17))
        self.groupBox_5 = QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 0, 521, 251))
        self.checkBox_56 = QCheckBox(self.groupBox_5)
        self.checkBox_56.setObjectName(u"checkBox_56")
        self.checkBox_56.setGeometry(QRect(20, 30, 41, 17))
        self.checkBox_57 = QCheckBox(self.groupBox_5)
        self.checkBox_57.setObjectName(u"checkBox_57")
        self.checkBox_57.setGeometry(QRect(20, 60, 31, 17))
        self.checkBox_58 = QCheckBox(self.groupBox_5)
        self.checkBox_58.setObjectName(u"checkBox_58")
        self.checkBox_58.setGeometry(QRect(20, 100, 31, 17))
        self.checkBox_59 = QCheckBox(self.groupBox_5)
        self.checkBox_59.setObjectName(u"checkBox_59")
        self.checkBox_59.setGeometry(QRect(20, 140, 51, 17))
        self.checkBox_60 = QCheckBox(self.groupBox_5)
        self.checkBox_60.setObjectName(u"checkBox_60")
        self.checkBox_60.setGeometry(QRect(20, 180, 51, 17))
        self.checkBox_61 = QCheckBox(self.groupBox_5)
        self.checkBox_61.setObjectName(u"checkBox_61")
        self.checkBox_61.setGeometry(QRect(60, 100, 41, 17))
        self.checkBox_62 = QCheckBox(self.groupBox_5)
        self.checkBox_62.setObjectName(u"checkBox_62")
        self.checkBox_62.setGeometry(QRect(60, 30, 41, 17))
        self.checkBox_63 = QCheckBox(self.groupBox_5)
        self.checkBox_63.setObjectName(u"checkBox_63")
        self.checkBox_63.setGeometry(QRect(60, 180, 41, 17))
        self.checkBox_64 = QCheckBox(self.groupBox_5)
        self.checkBox_64.setObjectName(u"checkBox_64")
        self.checkBox_64.setGeometry(QRect(60, 60, 41, 17))
        self.checkBox_65 = QCheckBox(self.groupBox_5)
        self.checkBox_65.setObjectName(u"checkBox_65")
        self.checkBox_65.setGeometry(QRect(60, 140, 41, 17))
        self.checkBox_66 = QCheckBox(self.groupBox_5)
        self.checkBox_66.setObjectName(u"checkBox_66")
        self.checkBox_66.setGeometry(QRect(110, 100, 41, 17))
        self.checkBox_67 = QCheckBox(self.groupBox_5)
        self.checkBox_67.setObjectName(u"checkBox_67")
        self.checkBox_67.setGeometry(QRect(110, 30, 41, 17))
        self.checkBox_68 = QCheckBox(self.groupBox_5)
        self.checkBox_68.setObjectName(u"checkBox_68")
        self.checkBox_68.setGeometry(QRect(110, 180, 41, 17))
        self.checkBox_69 = QCheckBox(self.groupBox_5)
        self.checkBox_69.setObjectName(u"checkBox_69")
        self.checkBox_69.setGeometry(QRect(110, 60, 41, 17))
        self.checkBox_70 = QCheckBox(self.groupBox_5)
        self.checkBox_70.setObjectName(u"checkBox_70")
        self.checkBox_70.setGeometry(QRect(110, 140, 41, 17))
        self.checkBox_71 = QCheckBox(self.groupBox_5)
        self.checkBox_71.setObjectName(u"checkBox_71")
        self.checkBox_71.setGeometry(QRect(150, 100, 41, 17))
        self.checkBox_72 = QCheckBox(self.groupBox_5)
        self.checkBox_72.setObjectName(u"checkBox_72")
        self.checkBox_72.setGeometry(QRect(150, 30, 41, 17))
        self.checkBox_73 = QCheckBox(self.groupBox_5)
        self.checkBox_73.setObjectName(u"checkBox_73")
        self.checkBox_73.setGeometry(QRect(150, 180, 41, 17))
        self.checkBox_74 = QCheckBox(self.groupBox_5)
        self.checkBox_74.setObjectName(u"checkBox_74")
        self.checkBox_74.setGeometry(QRect(150, 60, 41, 17))
        self.checkBox_75 = QCheckBox(self.groupBox_5)
        self.checkBox_75.setObjectName(u"checkBox_75")
        self.checkBox_75.setGeometry(QRect(150, 140, 41, 17))
        self.checkBox_76 = QCheckBox(self.groupBox_5)
        self.checkBox_76.setObjectName(u"checkBox_76")
        self.checkBox_76.setGeometry(QRect(190, 140, 41, 17))
        self.checkBox_77 = QCheckBox(self.groupBox_5)
        self.checkBox_77.setObjectName(u"checkBox_77")
        self.checkBox_77.setGeometry(QRect(190, 180, 41, 17))
        self.checkBox_78 = QCheckBox(self.groupBox_5)
        self.checkBox_78.setObjectName(u"checkBox_78")
        self.checkBox_78.setGeometry(QRect(190, 30, 41, 17))
        self.checkBox_79 = QCheckBox(self.groupBox_5)
        self.checkBox_79.setObjectName(u"checkBox_79")
        self.checkBox_79.setGeometry(QRect(190, 60, 41, 17))
        self.checkBox_80 = QCheckBox(self.groupBox_5)
        self.checkBox_80.setObjectName(u"checkBox_80")
        self.checkBox_80.setGeometry(QRect(190, 100, 41, 17))
        self.checkBox_81 = QCheckBox(self.groupBox_5)
        self.checkBox_81.setObjectName(u"checkBox_81")
        self.checkBox_81.setGeometry(QRect(230, 100, 41, 17))
        self.checkBox_82 = QCheckBox(self.groupBox_5)
        self.checkBox_82.setObjectName(u"checkBox_82")
        self.checkBox_82.setGeometry(QRect(230, 30, 41, 17))
        self.checkBox_83 = QCheckBox(self.groupBox_5)
        self.checkBox_83.setObjectName(u"checkBox_83")
        self.checkBox_83.setGeometry(QRect(230, 180, 41, 17))
        self.checkBox_84 = QCheckBox(self.groupBox_5)
        self.checkBox_84.setObjectName(u"checkBox_84")
        self.checkBox_84.setGeometry(QRect(230, 60, 41, 17))
        self.checkBox_85 = QCheckBox(self.groupBox_5)
        self.checkBox_85.setObjectName(u"checkBox_85")
        self.checkBox_85.setGeometry(QRect(230, 140, 41, 17))
        self.checkBox_86 = QCheckBox(self.groupBox_5)
        self.checkBox_86.setObjectName(u"checkBox_86")
        self.checkBox_86.setGeometry(QRect(270, 100, 41, 17))
        self.checkBox_87 = QCheckBox(self.groupBox_5)
        self.checkBox_87.setObjectName(u"checkBox_87")
        self.checkBox_87.setGeometry(QRect(270, 27, 41, 20))
        self.checkBox_88 = QCheckBox(self.groupBox_5)
        self.checkBox_88.setObjectName(u"checkBox_88")
        self.checkBox_88.setGeometry(QRect(270, 180, 51, 17))
        self.checkBox_89 = QCheckBox(self.groupBox_5)
        self.checkBox_89.setObjectName(u"checkBox_89")
        self.checkBox_89.setGeometry(QRect(270, 60, 41, 17))
        self.checkBox_90 = QCheckBox(self.groupBox_5)
        self.checkBox_90.setObjectName(u"checkBox_90")
        self.checkBox_90.setGeometry(QRect(270, 140, 51, 17))
        self.checkBox_91 = QCheckBox(self.groupBox_5)
        self.checkBox_91.setObjectName(u"checkBox_91")
        self.checkBox_91.setGeometry(QRect(310, 100, 41, 17))
        self.checkBox_92 = QCheckBox(self.groupBox_5)
        self.checkBox_92.setObjectName(u"checkBox_92")
        self.checkBox_92.setGeometry(QRect(310, 30, 41, 17))
        self.checkBox_93 = QCheckBox(self.groupBox_5)
        self.checkBox_93.setObjectName(u"checkBox_93")
        self.checkBox_93.setGeometry(QRect(310, 180, 41, 17))
        self.checkBox_94 = QCheckBox(self.groupBox_5)
        self.checkBox_94.setObjectName(u"checkBox_94")
        self.checkBox_94.setGeometry(QRect(310, 60, 41, 17))
        self.checkBox_95 = QCheckBox(self.groupBox_5)
        self.checkBox_95.setObjectName(u"checkBox_95")
        self.checkBox_95.setGeometry(QRect(310, 140, 41, 17))
        self.checkBox_96 = QCheckBox(self.groupBox_5)
        self.checkBox_96.setObjectName(u"checkBox_96")
        self.checkBox_96.setGeometry(QRect(350, 100, 41, 17))
        self.checkBox_97 = QCheckBox(self.groupBox_5)
        self.checkBox_97.setObjectName(u"checkBox_97")
        self.checkBox_97.setGeometry(QRect(350, 30, 41, 17))
        self.checkBox_98 = QCheckBox(self.groupBox_5)
        self.checkBox_98.setObjectName(u"checkBox_98")
        self.checkBox_98.setGeometry(QRect(350, 180, 41, 17))
        self.checkBox_99 = QCheckBox(self.groupBox_5)
        self.checkBox_99.setObjectName(u"checkBox_99")
        self.checkBox_99.setGeometry(QRect(350, 60, 41, 17))
        self.checkBox_100 = QCheckBox(self.groupBox_5)
        self.checkBox_100.setObjectName(u"checkBox_100")
        self.checkBox_100.setGeometry(QRect(350, 140, 41, 17))
        self.checkBox_101 = QCheckBox(self.groupBox_5)
        self.checkBox_101.setObjectName(u"checkBox_101")
        self.checkBox_101.setGeometry(QRect(390, 100, 41, 17))
        self.checkBox_102 = QCheckBox(self.groupBox_5)
        self.checkBox_102.setObjectName(u"checkBox_102")
        self.checkBox_102.setGeometry(QRect(390, 30, 51, 17))
        self.checkBox_103 = QCheckBox(self.groupBox_5)
        self.checkBox_103.setObjectName(u"checkBox_103")
        self.checkBox_103.setGeometry(QRect(390, 180, 41, 17))
        self.checkBox_104 = QCheckBox(self.groupBox_5)
        self.checkBox_104.setObjectName(u"checkBox_104")
        self.checkBox_104.setGeometry(QRect(390, 60, 41, 17))
        self.checkBox_105 = QCheckBox(self.groupBox_5)
        self.checkBox_105.setObjectName(u"checkBox_105")
        self.checkBox_105.setGeometry(QRect(390, 140, 41, 17))
        self.groupBox_4 = QGroupBox(Primitiva)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 10, 161, 61))
        self.radioButton = QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 30, 82, 17))
        self.radioButton_2 = QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(100, 30, 82, 17))
        self.label = QLabel(Primitiva)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 360, 47, 13))
        self.lineEdit = QLineEdit(Primitiva)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(110, 360, 113, 20))
        self.pushButton = QPushButton(Primitiva)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(240, 360, 101, 23))
        self.pushButton_2 = QPushButton(Primitiva)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(550, 360, 75, 23))
        self.lineEdit_2 = QLineEdit(Primitiva)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(270, 40, 113, 20))
        self.label_2 = QLabel(Primitiva)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(280, 20, 91, 16))
        self.label_3 = QLabel(Primitiva)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(480, 20, 51, 16))
        self.label_4 = QLabel(Primitiva)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(500, 40, 16, 16))
        self.lineEdit_3 = QLineEdit(Primitiva)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(450, 40, 41, 20))
        self.lineEdit_4 = QLineEdit(Primitiva)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(520, 40, 41, 20))

        self.retranslateUi(Primitiva)

        QMetaObject.connectSlotsByName(Primitiva)
    # setupUi

    def retranslateUi(self, Primitiva):
        Primitiva.setWindowTitle(QCoreApplication.translate("Primitiva", u"Primitiva", None))
        self.groupBox.setTitle(QCoreApplication.translate("Primitiva", u"Decenas", None))
        self.checkBox.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_2.setText(QCoreApplication.translate("Primitiva", u"10", None))
        self.checkBox_3.setText(QCoreApplication.translate("Primitiva", u"20", None))
        self.checkBox_4.setText(QCoreApplication.translate("Primitiva", u"30", None))
        self.checkBox_5.setText(QCoreApplication.translate("Primitiva", u"40", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Primitiva", u"Unidades", None))
        self.checkBox_6.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_7.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_8.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_9.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_10.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_11.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_12.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_13.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_14.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_15.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_16.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_17.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_18.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_19.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_20.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_21.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_22.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_23.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_24.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_25.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_30.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_28.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_27.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_29.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_26.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_31.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_32.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_33.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_34.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_35.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_36.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_37.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_38.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_39.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_40.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_41.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_42.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_43.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_44.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_45.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_46.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_47.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_48.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_49.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_50.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_51.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_52.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_53.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_54.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_55.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Primitiva", u"Unidades", None))
        self.checkBox_56.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_57.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_58.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_59.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_60.setText(QCoreApplication.translate("Primitiva", u"0", None))
        self.checkBox_61.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_62.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_63.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_64.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_65.setText(QCoreApplication.translate("Primitiva", u"1", None))
        self.checkBox_66.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_67.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_68.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_69.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_70.setText(QCoreApplication.translate("Primitiva", u"2", None))
        self.checkBox_71.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_72.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_73.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_74.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_75.setText(QCoreApplication.translate("Primitiva", u"3", None))
        self.checkBox_76.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_77.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_78.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_79.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_80.setText(QCoreApplication.translate("Primitiva", u"4", None))
        self.checkBox_81.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_82.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_83.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_84.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_85.setText(QCoreApplication.translate("Primitiva", u"5", None))
        self.checkBox_86.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_87.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_88.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_89.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_90.setText(QCoreApplication.translate("Primitiva", u"6", None))
        self.checkBox_91.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_92.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_93.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_94.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_95.setText(QCoreApplication.translate("Primitiva", u"7", None))
        self.checkBox_96.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_97.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_98.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_99.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_100.setText(QCoreApplication.translate("Primitiva", u"8", None))
        self.checkBox_101.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_102.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_103.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_104.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.checkBox_105.setText(QCoreApplication.translate("Primitiva", u"9", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Primitiva", u"Tipo de apuesta", None))
        self.radioButton.setText(QCoreApplication.translate("Primitiva", u"Automatica", None))
        self.radioButton_2.setText(QCoreApplication.translate("Primitiva", u"Manual", None))
        self.label.setText(QCoreApplication.translate("Primitiva", u"A cambiar", None))
        self.pushButton.setText(QCoreApplication.translate("Primitiva", u"Cambiar", None))
        self.pushButton_2.setText(QCoreApplication.translate("Primitiva", u"Validar", None))
        self.label_2.setText(QCoreApplication.translate("Primitiva", u"Total de apuestas", None))
        self.label_3.setText(QCoreApplication.translate("Primitiva", u"Apuesta", None))
        self.label_4.setText(QCoreApplication.translate("Primitiva", u"de", None))
    # retranslateUi

