<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contactos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dni">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{8}[A-Za-z]" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="nombre" type="xs:string" />
                <xs:element name="apellido1" type="xs:string" />
                <xs:element name="apellido2" type="xs:string" />

                <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[^@]+@[^\.]+\..+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="telefono" type="xs:string" />
                <xs:element name="mascota" type="xs:string" />

                <xs:element name="edad">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxExclusive value="120"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>