-- MySQL Script generated by MySQL Workbench
-- Thu Nov  6 12:37:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `num_social` INT NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `tlfno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `PK_CodPRO` INT NOT NULL,
  `Descripcion` VARCHAR(15) NOT NULL,
  `Fecha_inicio` DATETIME NOT NULL,
  `Fecha_fin` DATETIME NOT NULL,
  `Cuantia` INT NOT NULL,
  `Fk_DNI_CLI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PK_CodPRO`),
  INDEX `FK_DNi_CLI_idx` (`Fk_DNI_CLI` ASC) VISIBLE,
  CONSTRAINT `FK_DNi_CLI`
    FOREIGN KEY (`Fk_DNI_CLI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `PK_NIF` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(15) NOT NULL,
  `domicilio` VARCHAR(15) NOT NULL,
  `banco` VARCHAR(15) NOT NULL,
  `numero_cuenta` INT NOT NULL,
  `tlfno` INT NOT NULL,
  PRIMARY KEY (`PK_NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_pago` (
  `codtipopago` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codtipopago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `PK_ NumPago` INT NOT NULL,
  `concepto` VARCHAR(45) NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `FK_NIF_Colab` VARCHAR(9) NOT NULL,
  `FK_CodTipoPago` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PK_ NumPago`),
  INDEX `FK_NIF_Colab_idx` (`FK_NIF_Colab` ASC) VISIBLE,
  INDEX `FK_CodTipoPago_idx` (`FK_CodTipoPago` ASC) VISIBLE,
  CONSTRAINT `FK_NIF_Colab`
    FOREIGN KEY (`FK_NIF_Colab`)
    REFERENCES `mydb`.`Colaborador` (`PK_NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CodTipoPago`
    FOREIGN KEY (`FK_CodTipoPago`)
    REFERENCES `mydb`.`Tipo_pago` (`codtipopago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participan` (
  `PK_FK_NIF_Colab` VARCHAR(9) NOT NULL,
  `PK_FK_CodPro` INT NOT NULL,
  PRIMARY KEY (`PK_FK_NIF_Colab`, `PK_FK_CodPro`),
  INDEX `PK_FK_NIF_CodPro_idx` (`PK_FK_CodPro` ASC) VISIBLE,
  CONSTRAINT `PK_FK_NIF_CodPro`
    FOREIGN KEY (`PK_FK_CodPro`)
    REFERENCES `mydb`.`Proyecto` (`PK_CodPRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_FK_NIF_Colab`
    FOREIGN KEY (`PK_FK_NIF_Colab`)
    REFERENCES `mydb`.`Colaborador` (`PK_NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
