-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 22:28:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTAMENTO` (
  `CodDpto` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `Dni_jefe` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`CodDpto`, `nombre`),
  INDEX `Dni_jefe_idx` (`Dni_jefe` ASC) VISIBLE,
  UNIQUE INDEX `Dni_jefe_UNIQUE` (`Dni_jefe` ASC) VISIBLE,
  CONSTRAINT `Dni_jefe`
    FOREIGN KEY (`Dni_jefe`)
    REFERENCES `mydb`.`Profesor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `DNI` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(25) NOT NULL,
  `prAPELLIDO` VARCHAR(25) NOT NULL,
  `SGAPELLIDO` VARCHAR(25) NULL,
  `FK_CodDpto` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `CodDpto_idx` (`FK_CodDpto` ASC) VISIBLE,
  CONSTRAINT `CodDpto`
    FOREIGN KEY (`FK_CodDpto`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`CodDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `DNI` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `prAPELLIDO` VARCHAR(45) NOT NULL,
  `sgAPELLIDO` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CICLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CICLO` (
  `CODciclo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `siglas` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`CODciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASIGNATURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASIGNATURA` (
  `CODasig` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `NUMHORAS` INT UNSIGNED NOT NULL,
  `Bilingue` TINYINT NOT NULL,
  `FKCodCiclo` INT NOT NULL,
  PRIMARY KEY (`CODasig`),
  INDEX `FKCodCiclo_idx` (`FKCodCiclo` ASC) VISIBLE,
  CONSTRAINT `FKCodCiclo`
    FOREIGN KEY (`FKCodCiclo`)
    REFERENCES `mydb`.`CICLO` (`CODciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnobil` (
  `DNI` VARCHAR(9) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Lugarcert` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `DNi_alum`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Alumno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `Curso` DATETIME NOT NULL,
  `nota` INT NOT NULL,
  `DniAlu` VARCHAR(9) NOT NULL,
  `CodAsig` INT NOT NULL,
  CHECK (nota >= 1 AND nota <= 10),
  PRIMARY KEY (`Curso`),
  INDEX `Dnialu_idx` (`DniAlu` ASC) VISIBLE,
  INDEX `CodAsig_idx` (`CodAsig` ASC) VISIBLE,
  CONSTRAINT `Dnialu`
    FOREIGN KEY (`DniAlu`)
    REFERENCES `mydb`.`Alumno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodAsig`
    FOREIGN KEY (`CodAsig`)
    REFERENCES `mydb`.`ASIGNATURA` (`CODasig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMPARTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IMPARTE` (
  `DNI_Prof` VARCHAR(9) NOT NULL,
  `CodAsig` INT NOT NULL,
  `Curso` DATETIME NOT NULL,
  INDEX `DNI_Prof_idx` (`DNI_Prof` ASC) VISIBLE,
  INDEX `CodAsig_idx` (`CodAsig` ASC) VISIBLE,
  CONSTRAINT `DNI_Prof`
    FOREIGN KEY (`DNI_Prof`)
    REFERENCES `mydb`.`Profesor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodAsig`
    FOREIGN KEY (`CodAsig`)
    REFERENCES `mydb`.`ASIGNATURA` (`CODasig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
