-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 10:07:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ut5inicial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ut5inicial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ut5inicial` DEFAULT CHARACTER SET utf8mb3 ;
USE `ut5inicial` ;

-- -----------------------------------------------------
-- Table `ut5inicial`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ut5inicial`.`departamentos` (
  `NumDep` INT NOT NULL,
  `Nombre_Dep` VARCHAR(45) NOT NULL,
  `Localizacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NumDep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ut5inicial`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ut5inicial`.`empleados` (
  `EmplNum` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Genero` ENUM('M', 'V', 'X') NOT NULL,
  `Oficio` VARCHAR(45) NOT NULL,
  `Jefe` INT NULL DEFAULT NULL,
  `Alta` DATE NOT NULL,
  `Salario` INT NOT NULL,
  `Comision` INT NULL DEFAULT NULL,
  `Dpto` INT NOT NULL,
  PRIMARY KEY (`EmplNum`),
  INDEX `fk1_Dept_idx` (`Dpto` ASC) VISIBLE,
  INDEX `fk2_Director_idx` (`Jefe` ASC) VISIBLE,
  CONSTRAINT `fk1_Dept`
    FOREIGN KEY (`Dpto`)
    REFERENCES `ut5inicial`.`departamentos` (`NumDep`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2_jefe`
    FOREIGN KEY (`Jefe`)
    REFERENCES `ut5inicial`.`empleados` (`EmplNum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
