-- 2.1

CREATE USER 'ALUMNO_APP'@'localhost' identified by '12345';
GRANT SELECT (ALUMNO, CURSO, GRUPO) ON ACAD_IDIOMAS TO 'ALUMNO_APP'@'localhost';

-- 2.2

CREATE USER 'SECRETARIA'@'localhost' identified by '123456';
GRANT SELECT,INSERT,UPDATE,DELETE ON ACAD_IDIOMAS.* TO 'SECRETARIA'@'localhost';

-- 2.3

CREATE USER 'DIRECCION'@'localhost' identified by '1234567';
GRANT ALL PRIVILEGES ON *.* TO 'SECRETARIA'@'localhost';

-- 2.4

CREATE USER 'PROFESOR_ING'@'localhost' identified by 'profesor1';
GRANT SELECT (NOMBRE, APELLIDOS) ON ACAD_IDIOMAS.ALUMNO TO 'PROFESOR_ING'@'localhost';

-- 2.5

REVOKE SELECT ON ACAD_IDIOMAS.PAGO FROM 'ALUMNO_APP'@'localhost';



