CREATE SCHEMA IF NOT EXISTS ACAD_IDIOMAS DEFAULT CHARACTER SET latin1;
USE ACAD_IDIOMAS;

CREATE TABLE IF NOT EXISTS ALUMNO (
    ID_ALUMNO VARCHAR(3),
    DNI VARCHAR(9) NOT NULL UNIQUE,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(45) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO INT,
    EMAIL VARCHAR(30),
    PRIMARY KEY(ID_ALUMNO)
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CURSO(
    ID_CURSO VARCHAR(3),
    IDIOMA ENUM("INGLES","FRANCES","ALEMAN", "RUMANO"),
    NIVEL ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'),
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    PLAZAS_MAXIMAS INT UNSIGNED,
    PRIMARY KEY(ID_CURSO)
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PROFESOR(
    ID_PROFESOR VARCHAR(3),
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(45) NOT NULL,
    ESPECIALIDAD_IDIOMA TEXT NOT NULL,
    PRIMARY KEY(ID_PROFESOR)
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS GRUPO(
    ID_GRUPO VARCHAR(3), 
    ID_CURSO VARCHAR(3), -- FK REFE TABLA CURSO
    ID_PROFESOR VARCHAR(3), -- FK REFE TABLA PROFESOR
    HORARIO TEXT NOT NULL,
    PRIMARY KEY(ID_GRUPO),
    CONSTRAINT FK_ID_CURSO1 FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID_CURSO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_ID_PROFESOR FOREIGN KEY(ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS MATRICULA(
    ID_ALUMNO VARCHAR(3),-- FK REFE TABLA ALUMNO
    ID_CURSO VARCHAR(3), -- FK REFE TABLA CURSO
    ANIO_ACADEMICO VARCHAR(9),
    FECHA_MARTRICULA DATE NOT NULL,
    FORMA_PAGO TEXT NOT NULL,
    PRIMARY KEY (ID_ALUMNO, ID_CURSO, ANIO_ACADEMICO),
    CONSTRAINT FK_ID_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_ID_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS  PAGO(
    ID_PAGO int AUTO_INCREMENT,
    ID_ALUMNO VARCHAR(3), -- FK REFE TABLA ALUMNO
    ID_CURSO VARCHAR(3), -- FK REFE TABLA CURSO
    ANIO_ACADEMICO VARCHAR(9),
    fecha_pago DATE NOT NULL,
    IMPORTE FLOAT NOT NULL,
    PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_ID_ALUMNO FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_ID_CURSO FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID_CURSO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_ANIO_ACADEMICO FOREIGN KEY(ANIO_ACADEMICO) REFERENCES MATRICULA(ANIO_ACADEMICO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) Engine = InnoDB;


